// read package.json and get version
import fs from "fs";

export function getPackageInfo() :{
    version: string,
    author: string,
} {
    const packageJson = fs.readFileSync("./package.json", "utf8");
    const packageJsonObject = JSON.parse(packageJson);

    return {
        version: packageJsonObject.version || "[unknown version]",
        author: packageJsonObject.author || "justin26l",
    };
}

export function getGenaratorHeaderComment(depedencies?:string) :string{
    if(!depedencies){
        depedencies = '';
    }
    const packageInfo = getPackageInfo();
    return`/* eslint-disable */
/**
 * Generated by json2mongoose@${packageInfo.version} ${depedencies}.
 * DO NOT MODIFY MANUALLY. Instead, modify the source JSONSchema file,
 * and run json2mongoose to regenerate this file.
 * 
 * author: ${packageInfo.author}
 * version: ${packageInfo.version}
 */
`;

}

export const defaultCompilerOptions = {
    headerComment: getGenaratorHeaderComment(),
};

export default {
    getPackageInfo,
    getGenaratorHeaderComment,
    defaultCompilerOptions,
};
