import pkg from "../package.json";

export function getGenaratorHeaderComment(depedencies?:string) :string{
    if(!depedencies){
        depedencies = "";
    }
    return`/* eslint-disable */
/**
 * Generated by json2mongoose@${pkg.version} ${depedencies}.
 * DO NOT MODIFY MANUALLY. Instead, modify the source JSONSchema file,
 * and run json2mongoose to regenerate this file.
 * 
 * author: ${pkg.author}
 * version: ${pkg.version}
 */
`;

}

export const defaultCompilerOptions = {
    headerComment: getGenaratorHeaderComment(),
    use_id: false,
};

export default {
    getGenaratorHeaderComment,
    defaultCompilerOptions,
};
